server:
  port: 8000
  servlet:
    context-path: /consul-provider #配置项目名
spring:
  cloud:
    consul:
      host: localhost # consul 服务端的 ip
      port: 8500 # consul 服务端的端口 默认8500
      discovery:
        service-name: ${spring.application.name} # 当前应用注册到consul的名称
        prefer-ip-address: true # 是否以ip形式注册
  application:
    name: consul-provider # 应用名称
