server:
  port: 8082  #自定义监听端口,默认8080

# RocketMQ相关配置
rocketmq:
  name-server: 127.0.0.1:9876

spring:
  application:
    name: my-mqconsumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: lwd
    password: lwd
    listener:
      simple:
        prefetch: 1   #负载均衡参数，一次接收一条消息
        acknowledge-mode: auto   # 指定消息确认模式
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000 # 初始的失败等待时长为1秒
          multiplier: 3 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 4 # 最大重试次数
  cloud:
    nacos: #nacos注册中心配置
      discovery:
        server-addr: 127.0.0.1:8848 # 配置nacos 服务端地址
dubbo:
  registry:
    address: spring-cloud://localhost  #使用springcloud中注册中心的地址
  consumer:
    check: false
  protocol:
    port: 20885
    name: dubbo