spring:
  #数据源配置
  datasource:
    #druid:
      url: jdbc:mysql://localhost:3306/adolesce?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      minIdle: 30
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
  #spring data jpa配置
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          #create：每次加载 hibernate删除表，根据modal新生成表
          #create-drop：每次加载 hibernate删除表，根据modal新生成表，但是sessionFactory 一关闭,表就自动删除
          #update：常用，第一次加载 hibernate 时根据 model 类会自动建立起表的结构（前提是先建立好数据库），以后加载 hibernate 时根据 model 类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行
          #validate ：每次加载 hibernate 时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值。
          auto: update
        #指定生成表名的存储引擎为 InnoDBD
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #是否打印出自动生成的 SQL，方便调试的时候查看
    show-sql: true
  #redis配置
  redis:
    database: 0             #数据库索引（默认为0）
    host: 192.168.56.1  #服务器地址
    port: 6379              #服务器连接端口(默认)
    password: lwd               #服务器连接密码 (默认为空 没有不填)
    timeout: 10s          #连接超时时间（秒）
    jedis:
      pool:
        max-active: 500       #连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: 10000ms        #连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 100         #连接池中的最大空闲连接 默认 8
        min-idle: 0           #连接池中的最小空闲连接 默认 0
  #MongoDB配置
  data:
    mongodb:
      username: lwd
      password: lwd
      authentication-database: admin
      database: adolesce
      port: 27017
      host: 127.0.0.1
      #uri: mongodb://127.0.0.1:27017/adolesce   #无权限设置

jwt:
  secret: 76bd425b6f29f7fcc2e0bfc286043df1
#是否开启数据缓存
cache:
  enable: true
