server:
  port: 3004  #自定义监听端口,默认8080

spring:
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
dubbo:
  registry:
    address: spring-cloud://localhost  #使用springcloud中注册中心的地址
  scan:
    base-packages: com.adolesce.cloud.es.api
  protocol:
    name: dubbo
    port: 20882
  consumer:
    check: false
    retries: 0

#日志
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS

# ES相关配置
elasticsearch:
  host: 127.0.0.1
  port: 9200